apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
  namespace: ecom
data:
  01_create_dbs.sql: |
    create database if not exists ecom_user;
    create database if not exists ecom_product;
    create database if not exists ecom_cart;
    create database if not exists ecom_order;
    create database if not exists ecom_payment;
    create database if not exists ecom_messaging;
    create database if not exists keycloak;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: ecom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: ecom
            - name: MYSQL_PASSWORD
              value: ecom
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: initdb
          configMap:
            name: mysql-init
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: ecom
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
