server:
  port: 8084

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://mysql:3306/ecom_order?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ecom
    password: ecom
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/ecom}

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://zipkin:9411/api/v2/spans}

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/


spring:
  kafka:
    bootstrap-servers: kafka:9092
outbox:
  publisher:
    delay-ms: 2000

